name: 🚀 Feature
description: 'Submit a proposal for a new feature'
title: '🚀 Feature: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature for Harness plugins for Backstage!
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: '🔖 Feature description'
      description: 'A clear and concise description of what the feature is.'
      placeholder: 'There should be a ...'
  - type: textarea
    id: context
    validations:
      required: true
    attributes:
      label: '🎤 Context'
      description: 'Please explain why this feature should be implemented and how it would be used. Add examples, if applicable.'
      placeholder: 'In my use-case, ...'
  - type: textarea
    id: implementation
    attributes:
      label: '✌️ Possible Implementation'
      description: 'A clear and concise description of what you want to happen.'
      placeholder: 'Not obligatory, but ideas as to the implementation of the addition or change'
  - type: dropdown
    id: willing-to-submit-pr
    attributes:
      label: Are you willing to submit PR?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - Yes I am willing to submit a PR!
        - No, but I'm happy to collaborate on a PR with someone else
        - No, I don't have time to work on this right now
